title: Site

sections:
  test:
    type: pages
    label: Pieces
    parent: kirby.page('pieces')
    layout: cards
    template: piece
    image:
      query: page.images.first
      ratio: 3/2
      cover: true
  pages:
    type: pages
    status: listed
    layout: list
    image:
      back: white
info: "{{ page.year }}"
#this line above seems to have deleted the option to edit the site description
  fields:
    type: fields
    fields:
      Description:
        type: textarea


staticSiteGenerator:
   label: Generate static site
   help: Custom help text
   progress: Custom please-wait message
   success: Custom success message
   error: Custom error message
   # ... (see "Field options")
