title: Site

sections:
  generator:
    type: fields
    fields:
      staticSiteGenerator:
        label: Generate a static version of the site
  pieces:
    type: pages
    label: Pieces
    parent: kirby.page('pieces')
    layout: cards
    template: piece
    image:
      query: page.images.first
      ratio: 3/2
      cover: true
  pages:
    type: pages
    status: listed
    layout: list
    image:
      back: white
  info: "{{ page.year }}" # what is this field for?
  description:
    type: fields
    fields:
      Description:
        type: textarea
